// <auto-generated />
using System;
using LeagueTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeagueTracker.Api.Data.Migrations
{
    [DbContext(typeof(LeagueDbContext))]
    [Migration("20260903122421_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeagueTracker.Api.Data.Death", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AlliesNearDeath")
                        .HasColumnType("integer");

                    b.Property<string>("AssistedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Bounty")
                        .HasColumnType("integer");

                    b.Property<string>("DamageFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DamageInstanceCount")
                        .HasColumnType("integer");

                    b.Property<int?>("EnemiesNearDeath")
                        .HasColumnType("integer");

                    b.Property<int>("EnemiesOnYou")
                        .HasColumnType("integer");

                    b.Property<bool?>("EnemyJunglerNear")
                        .HasColumnType("boolean");

                    b.Property<int?>("FollowAlliesDownBefore")
                        .HasColumnType("integer");

                    b.Property<int?>("FollowDistance")
                        .HasColumnType("integer");

                    b.Property<bool?>("FollowPureLoss")
                        .HasColumnType("boolean");

                    b.Property<int?>("FollowSecondsAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("FollowTeamGoldDiff")
                        .HasColumnType("integer");

                    b.Property<string>("FollowTeammate")
                        .HasColumnType("text");

                    b.Property<string>("FollowTeammateCaughtBy")
                        .HasColumnType("text");

                    b.Property<string>("FollowTeammateRole")
                        .HasColumnType("text");

                    b.Property<string>("KilledBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MyCs")
                        .HasColumnType("integer");

                    b.Property<int?>("MyLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("MyTotalGold")
                        .HasColumnType("integer");

                    b.Property<int?>("NearestAllyDist")
                        .HasColumnType("integer");

                    b.Property<string>("ObjectiveBefore")
                        .HasColumnType("text");

                    b.Property<int?>("SecondsAfterObjective")
                        .HasColumnType("integer");

                    b.Property<int>("Shutdown")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSec")
                        .HasColumnType("integer");

                    b.Property<string>("TopSource")
                        .HasColumnType("text");

                    b.Property<double?>("TopSourceShare")
                        .HasColumnType("double precision");

                    b.Property<int?>("TotalDamageReceived")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Deaths");
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.DeathDamage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DeathId")
                        .HasColumnType("bigint");

                    b.Property<int>("Magic")
                        .HasColumnType("integer");

                    b.Property<int>("Physical")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpellName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrueDamage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeathId");

                    b.ToTable("DeathDamages");
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.ItemEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeSec")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("ItemEvents");
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.KeyValue", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("KeyValues");
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.KillEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AssistIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DamagePids")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KillerParticipantId")
                        .HasColumnType("integer");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeSec")
                        .HasColumnType("integer");

                    b.Property<int>("VictimParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("KillEvents");
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.KnownMatch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KnownMatches");
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.LpSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("Lp")
                        .HasColumnType("integer");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RankValue")
                        .HasColumnType("integer");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Queue", "TimestampUtc");

                    b.ToTable("LpSnapshots");
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AllyJungler")
                        .HasColumnType("text");

                    b.Property<int>("AllyRanksKnown")
                        .HasColumnType("integer");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<double?>("AvgAllyRankValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("AvgEnemyRankValue")
                        .HasColumnType("double precision");

                    b.Property<int?>("AvgNearestAllyDist")
                        .HasColumnType("integer");

                    b.Property<int?>("AvgUnspentGold")
                        .HasColumnType("integer");

                    b.Property<string>("ChallengesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChampLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Champion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContestedEpicsTaken")
                        .HasColumnType("integer");

                    b.Property<int>("ControlWards")
                        .HasColumnType("integer");

                    b.Property<int>("Cs")
                        .HasColumnType("integer");

                    b.Property<int?>("CsAt10")
                        .HasColumnType("integer");

                    b.Property<int?>("CsAt14")
                        .HasColumnType("integer");

                    b.Property<int?>("CsAt15")
                        .HasColumnType("integer");

                    b.Property<double?>("DamageTakenPerMin")
                        .HasColumnType("double precision");

                    b.Property<int>("DamageToChampions")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<double?>("DpmEarly")
                        .HasColumnType("double precision");

                    b.Property<double?>("DpmLate")
                        .HasColumnType("double precision");

                    b.Property<double?>("DpmMid")
                        .HasColumnType("double precision");

                    b.Property<double>("DurationSec")
                        .HasColumnType("double precision");

                    b.Property<string>("EnemyJungler")
                        .HasColumnType("text");

                    b.Property<int>("EnemyRanksKnown")
                        .HasColumnType("integer");

                    b.Property<string>("FightsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FirstControlWardSec")
                        .HasColumnType("integer");

                    b.Property<bool?>("FirstToLevel2")
                        .HasColumnType("boolean");

                    b.Property<int?>("FirstWardSec")
                        .HasColumnType("integer");

                    b.Property<int>("FollowInDeaths")
                        .HasColumnType("integer");

                    b.Property<int>("FriendlyEpicObjectives")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GameCreationUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GameEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<bool>("HasTimeline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRanked")
                        .HasColumnType("boolean");

                    b.Property<double?>("KillParticipation")
                        .HasColumnType("double precision");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int?>("LaneCsDiff10")
                        .HasColumnType("integer");

                    b.Property<int?>("LaneCsDiff15")
                        .HasColumnType("integer");

                    b.Property<string>("LaneDiffsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LaneGoldDiff10")
                        .HasColumnType("integer");

                    b.Property<int?>("LaneGoldDiff15")
                        .HasColumnType("integer");

                    b.Property<int?>("LaneXpDiff10")
                        .HasColumnType("integer");

                    b.Property<int?>("LaneXpDiff15")
                        .HasColumnType("integer");

                    b.Property<int?>("Level11LeadSec")
                        .HasColumnType("integer");

                    b.Property<int?>("Level16LeadSec")
                        .HasColumnType("integer");

                    b.Property<int?>("Level6LeadSec")
                        .HasColumnType("integer");

                    b.Property<string>("LevelSecs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LongestTimeSpentLiving")
                        .HasColumnType("integer");

                    b.Property<string>("LpAfter")
                        .HasColumnType("text");

                    b.Property<string>("LpBefore")
                        .HasColumnType("text");

                    b.Property<int?>("LpChange")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxUnspentGold")
                        .HasColumnType("integer");

                    b.Property<int>("ObjectivesPresentFor")
                        .HasColumnType("integer");

                    b.Property<string>("OpponentChampion")
                        .HasColumnType("text");

                    b.Property<int>("PentaKills")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuadraKills")
                        .HasColumnType("integer");

                    b.Property<int>("QueueId")
                        .HasColumnType("integer");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RanksAtGameTime")
                        .HasColumnType("boolean");

                    b.Property<string>("RawPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillOrder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SkillshotsDodged")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillshotsHit")
                        .HasColumnType("integer");

                    b.Property<int>("SoloKills")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamGoldDiff15")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamGoldDiff20")
                        .HasColumnType("integer");

                    b.Property<double?>("TimeInEnemyHalfPct")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalTimeCcDealt")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTimeSpentDead")
                        .HasColumnType("integer");

                    b.Property<int>("TripleKills")
                        .HasColumnType("integer");

                    b.Property<int>("VisionScore")
                        .HasColumnType("integer");

                    b.Property<int>("WardsFirst10")
                        .HasColumnType("integer");

                    b.Property<int>("WardsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("WardsPlaced")
                        .HasColumnType("integer");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GameEndUtc");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.MatchParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("ChampLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Champion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Cs")
                        .HasColumnType("integer");

                    b.Property<int>("DamageToChampions")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<string>("Division")
                        .HasColumnType("text");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAlly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMe")
                        .HasColumnType("boolean");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KeystoneId")
                        .HasColumnType("integer");

                    b.Property<double?>("KillParticipation")
                        .HasColumnType("double precision");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int?>("Lp")
                        .HasColumnType("integer");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<string>("PerksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PingsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrimaryStyleId")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RankQueue")
                        .HasColumnType("text");

                    b.Property<int?>("RankValue")
                        .HasColumnType("integer");

                    b.Property<string>("RiotId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SeasonLosses")
                        .HasColumnType("integer");

                    b.Property<int?>("SeasonWins")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillshotDodgesLateWindow")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillshotsDodged")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillshotsHit")
                        .HasColumnType("integer");

                    b.Property<int>("Spell1Casts")
                        .HasColumnType("integer");

                    b.Property<int>("Spell2Casts")
                        .HasColumnType("integer");

                    b.Property<int>("Spell3Casts")
                        .HasColumnType("integer");

                    b.Property<int>("Spell4Casts")
                        .HasColumnType("integer");

                    b.Property<int>("SubStyleId")
                        .HasColumnType("integer");

                    b.Property<int>("Summoner1Casts")
                        .HasColumnType("integer");

                    b.Property<int>("Summoner1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Summoner2Casts")
                        .HasColumnType("integer");

                    b.Property<int>("Summoner2Id")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Tier")
                        .HasColumnType("text");

                    b.Property<int>("VisionScore")
                        .HasColumnType("integer");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.ObjectiveEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("ByMyTeam")
                        .HasColumnType("boolean");

                    b.Property<int>("KillerParticipantId")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeSec")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("ObjectiveEvents");
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.PositionSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSec")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "TimeSec");

                    b.ToTable("PositionSamples");
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.Death", b =>
                {
                    b.HasOne("LeagueTracker.Api.Data.Match", null)
                        .WithMany("DeathEvents")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.DeathDamage", b =>
                {
                    b.HasOne("LeagueTracker.Api.Data.Death", null)
                        .WithMany("DamageInstances")
                        .HasForeignKey("DeathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.ItemEvent", b =>
                {
                    b.HasOne("LeagueTracker.Api.Data.Match", null)
                        .WithMany("ItemEvents")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.KillEvent", b =>
                {
                    b.HasOne("LeagueTracker.Api.Data.Match", null)
                        .WithMany("KillEvents")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.MatchParticipant", b =>
                {
                    b.HasOne("LeagueTracker.Api.Data.Match", null)
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.ObjectiveEvent", b =>
                {
                    b.HasOne("LeagueTracker.Api.Data.Match", null)
                        .WithMany("ObjectiveEvents")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.PositionSample", b =>
                {
                    b.HasOne("LeagueTracker.Api.Data.Match", null)
                        .WithMany("PositionSamples")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.Death", b =>
                {
                    b.Navigation("DamageInstances");
                });

            modelBuilder.Entity("LeagueTracker.Api.Data.Match", b =>
                {
                    b.Navigation("DeathEvents");

                    b.Navigation("ItemEvents");

                    b.Navigation("KillEvents");

                    b.Navigation("ObjectiveEvents");

                    b.Navigation("Participants");

                    b.Navigation("PositionSamples");
                });
#pragma warning restore 612, 618
        }
    }
}
